### 合集列表
#GET {{video-host}}{{video-port}}/drama
GET {{video-host}}{{video-port}}/drama?keyword=fate&page=1&per_page=1

### 创建合集
POST {{video-host}}{{video-port}}/drama
Content-Type: application/json

{
  "category_id": 1,
  "region_id": 1,
  "name": "新剧",
  "introduce": "新剧简介"
}

### 修改合集
PUT {{video-host}}{{video-port}}/drama/3
Content-Type: application/json

{
  "name": "某科学的超电磁炮",
  "introduce": ""
}

### 删除合集
DELETE {{video-host}}{{video-port}}/drama


### 添加分集
POST {{video-host}}{{video-port}}/drama/3/episode
Content-Type: application/json

{
  "episode": 2,
  "category_id": 1,
  "file_id": 1,
  "name": "测试分集2",
  "introduce": "分集简介",
  "cover": "https://www.baidu.com"
}

### 修改分集
PUT {{video-host}}{{video-port}}/drama/3/episode/6
Content-Type: application/json

{
  "name": "测试重复分集",
  "episode": 41
}