apiVersion: v1
kind: Service
metadata:
  name: video-web-server
spec:
  selector:
    app: video-web-server
  ports:
    - name: http-video-web-server
      protocol: TCP
      port: 9702
      targetPort: 9501
  type: LoadBalancer