// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: barrage.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BarrageClient is the client API for Barrage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BarrageClient interface {
	Create(ctx context.Context, in *UpdateBarrageRequest, opts ...grpc.CallOption) (*BarrageResponse, error)
	Update(ctx context.Context, in *UpdateBarrageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Delete(ctx context.Context, in *UpdateBarrageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Get(ctx context.Context, in *GetBarragesRequest, opts ...grpc.CallOption) (*GetBarrageResponse, error)
}

type barrageClient struct {
	cc grpc.ClientConnInterface
}

func NewBarrageClient(cc grpc.ClientConnInterface) BarrageClient {
	return &barrageClient{cc}
}

func (c *barrageClient) Create(ctx context.Context, in *UpdateBarrageRequest, opts ...grpc.CallOption) (*BarrageResponse, error) {
	out := new(BarrageResponse)
	err := c.cc.Invoke(ctx, "/video.pb.Barrage/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *barrageClient) Update(ctx context.Context, in *UpdateBarrageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/video.pb.Barrage/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *barrageClient) Delete(ctx context.Context, in *UpdateBarrageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/video.pb.Barrage/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *barrageClient) Get(ctx context.Context, in *GetBarragesRequest, opts ...grpc.CallOption) (*GetBarrageResponse, error) {
	out := new(GetBarrageResponse)
	err := c.cc.Invoke(ctx, "/video.pb.Barrage/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BarrageServer is the server API for Barrage service.
// All implementations must embed UnimplementedBarrageServer
// for forward compatibility
type BarrageServer interface {
	Create(context.Context, *UpdateBarrageRequest) (*BarrageResponse, error)
	Update(context.Context, *UpdateBarrageRequest) (*emptypb.Empty, error)
	Delete(context.Context, *UpdateBarrageRequest) (*emptypb.Empty, error)
	Get(context.Context, *GetBarragesRequest) (*GetBarrageResponse, error)
	mustEmbedUnimplementedBarrageServer()
}

// UnimplementedBarrageServer must be embedded to have forward compatible implementations.
type UnimplementedBarrageServer struct {
}

func (UnimplementedBarrageServer) Create(context.Context, *UpdateBarrageRequest) (*BarrageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedBarrageServer) Update(context.Context, *UpdateBarrageRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedBarrageServer) Delete(context.Context, *UpdateBarrageRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedBarrageServer) Get(context.Context, *GetBarragesRequest) (*GetBarrageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedBarrageServer) mustEmbedUnimplementedBarrageServer() {}

// UnsafeBarrageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BarrageServer will
// result in compilation errors.
type UnsafeBarrageServer interface {
	mustEmbedUnimplementedBarrageServer()
}

func RegisterBarrageServer(s grpc.ServiceRegistrar, srv BarrageServer) {
	s.RegisterService(&Barrage_ServiceDesc, srv)
}

func _Barrage_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBarrageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BarrageServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/video.pb.Barrage/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BarrageServer).Create(ctx, req.(*UpdateBarrageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Barrage_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBarrageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BarrageServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/video.pb.Barrage/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BarrageServer).Update(ctx, req.(*UpdateBarrageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Barrage_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBarrageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BarrageServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/video.pb.Barrage/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BarrageServer).Delete(ctx, req.(*UpdateBarrageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Barrage_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBarragesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BarrageServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/video.pb.Barrage/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BarrageServer).Get(ctx, req.(*GetBarragesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Barrage_ServiceDesc is the grpc.ServiceDesc for Barrage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Barrage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "video.pb.Barrage",
	HandlerType: (*BarrageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Barrage_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Barrage_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Barrage_Delete_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Barrage_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "barrage.proto",
}
