// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: episodes.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EpisodesClient is the client API for Episodes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EpisodesClient interface {
	Create(ctx context.Context, in *UpdateEpisodesRequest, opts ...grpc.CallOption) (*EpisodesResponse, error)
	Update(ctx context.Context, in *UpdateEpisodesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Delete(ctx context.Context, in *UpdateEpisodesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetDetail(ctx context.Context, in *GetEpisodesRequest, opts ...grpc.CallOption) (*EpisodesResponse, error)
	Get(ctx context.Context, in *GetEpisodesRequest, opts ...grpc.CallOption) (*EpisodesListResponse, error)
}

type episodesClient struct {
	cc grpc.ClientConnInterface
}

func NewEpisodesClient(cc grpc.ClientConnInterface) EpisodesClient {
	return &episodesClient{cc}
}

func (c *episodesClient) Create(ctx context.Context, in *UpdateEpisodesRequest, opts ...grpc.CallOption) (*EpisodesResponse, error) {
	out := new(EpisodesResponse)
	err := c.cc.Invoke(ctx, "/video.pb.Episodes/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *episodesClient) Update(ctx context.Context, in *UpdateEpisodesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/video.pb.Episodes/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *episodesClient) Delete(ctx context.Context, in *UpdateEpisodesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/video.pb.Episodes/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *episodesClient) GetDetail(ctx context.Context, in *GetEpisodesRequest, opts ...grpc.CallOption) (*EpisodesResponse, error) {
	out := new(EpisodesResponse)
	err := c.cc.Invoke(ctx, "/video.pb.Episodes/GetDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *episodesClient) Get(ctx context.Context, in *GetEpisodesRequest, opts ...grpc.CallOption) (*EpisodesListResponse, error) {
	out := new(EpisodesListResponse)
	err := c.cc.Invoke(ctx, "/video.pb.Episodes/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EpisodesServer is the server API for Episodes service.
// All implementations must embed UnimplementedEpisodesServer
// for forward compatibility
type EpisodesServer interface {
	Create(context.Context, *UpdateEpisodesRequest) (*EpisodesResponse, error)
	Update(context.Context, *UpdateEpisodesRequest) (*emptypb.Empty, error)
	Delete(context.Context, *UpdateEpisodesRequest) (*emptypb.Empty, error)
	GetDetail(context.Context, *GetEpisodesRequest) (*EpisodesResponse, error)
	Get(context.Context, *GetEpisodesRequest) (*EpisodesListResponse, error)
	mustEmbedUnimplementedEpisodesServer()
}

// UnimplementedEpisodesServer must be embedded to have forward compatible implementations.
type UnimplementedEpisodesServer struct {
}

func (UnimplementedEpisodesServer) Create(context.Context, *UpdateEpisodesRequest) (*EpisodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedEpisodesServer) Update(context.Context, *UpdateEpisodesRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedEpisodesServer) Delete(context.Context, *UpdateEpisodesRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedEpisodesServer) GetDetail(context.Context, *GetEpisodesRequest) (*EpisodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDetail not implemented")
}
func (UnimplementedEpisodesServer) Get(context.Context, *GetEpisodesRequest) (*EpisodesListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedEpisodesServer) mustEmbedUnimplementedEpisodesServer() {}

// UnsafeEpisodesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EpisodesServer will
// result in compilation errors.
type UnsafeEpisodesServer interface {
	mustEmbedUnimplementedEpisodesServer()
}

func RegisterEpisodesServer(s grpc.ServiceRegistrar, srv EpisodesServer) {
	s.RegisterService(&Episodes_ServiceDesc, srv)
}

func _Episodes_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEpisodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EpisodesServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/video.pb.Episodes/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EpisodesServer).Create(ctx, req.(*UpdateEpisodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Episodes_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEpisodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EpisodesServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/video.pb.Episodes/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EpisodesServer).Update(ctx, req.(*UpdateEpisodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Episodes_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEpisodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EpisodesServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/video.pb.Episodes/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EpisodesServer).Delete(ctx, req.(*UpdateEpisodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Episodes_GetDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEpisodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EpisodesServer).GetDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/video.pb.Episodes/GetDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EpisodesServer).GetDetail(ctx, req.(*GetEpisodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Episodes_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEpisodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EpisodesServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/video.pb.Episodes/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EpisodesServer).Get(ctx, req.(*GetEpisodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Episodes_ServiceDesc is the grpc.ServiceDesc for Episodes service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Episodes_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "video.pb.Episodes",
	HandlerType: (*EpisodesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Episodes_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Episodes_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Episodes_Delete_Handler,
		},
		{
			MethodName: "GetDetail",
			Handler:    _Episodes_GetDetail_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Episodes_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "episodes.proto",
}
